import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dream Match",
  description: "Generated by Tika Jeremias",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        {/* Background */}
        <main className="h-full w-full bg-neutral-900 bg-opacity-50 font-bold flex justify-center items-center">

          {/* Glassmorphism */}
          {children}

        </main>

      </body>
    </html>
  );
}
